name: 'build-test'
on: # rebuild any PRs and main branch changes
  pull_request:
  push:
    branches:
      - main
      - 'releases/*'

jobs:
  build: # make sure build/ci work properly
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - run: |
          npm install
      - run: |
          npm run all
  test: # make sure the action works on a clean machine without building
    runs-on: ubuntu-latest
    services:
      mockserver:
        image: mockserver/mockserver
        ports:
          - 1080/tcp
        env:
          MOCKSERVER_INITIALIZATION_JSON_PATH: /config/initializerJson.json
        volumes:
          - mockserver.json:/config/initializerJson.json
    steps:
      - uses: actions/checkout@v2
      - uses: ./
        id: promote
        with:
          url: http://localhost:${{ job.services.mockserver.ports['1080'] }}
          sourceRepo: docker-dev
          targetRepo: docker-prod
          dockerRepository: library/base
          tag: main
          targetTag: v1
      - name: echo output variable
        if: success() && steps.promote.outputs.image
        run: echo "Promoted image ${{ steps.promote.outputs.image }}"
      - name: troubleshoot service container
        if: always()
        run: |
            docker logs ${{ job.services.mockserver.id }}
            docker exec ${{ job.services.mockserver.id }} cat /config/initializerJson.json
